requires 'Plack', '1.0030';
requires 'DBI', '1.6';
requires 'Amon2::Lite';
requires 'File::Spec';
requires 'File::Basename';
requires 'Digest::MD5';
requires 'Amon2::Plugin::Web::JSON';
requires 'Amon2::DBI';
requires 'DBD::mysql';
requires 'DBIx::Sunny';
